### ISSUE TITLE
jkn2.smblott.org is broken

### ISSUE THREAD

**Issue by DreadBoy** [smblott-github/jk-navigator-too#2]
As title says, http://jkn2.smblott.org/ shows default Apache page and links to rulesets are 404.

**Comment by smblott-github** [comment]
Shoot.

Sorry about that.

I got a new machine and forgot to migrate the JKN2 web page.

Thanks for the report.  Should be fixed now.

Steve

**Comment by DreadBoy** [comment]
http://jkn2.smblott.org/ is 403 now but rules' pages work :)

**Comment by gmathrubootham** [comment]
Looks like the website is broken again.
